language: java
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.4
before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    linux)
      sudo apt-get update -qq
      sudo apt-get install -qq fakeroot
      curl https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -o gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
      tar xfj gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -C ~/
      rm gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
      ls ~/gcc-arm-none-eabi-7-2018-q2-update/bin
      curl https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb > java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      dpkg -i java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      export JAVA_HOME="/usr/lib/jvm/java-1.8.0-amazon-corretto"
      rm java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      env PATH="$PATH:~/gcc-arm-none-eabi-7-2018-q2-update/bin" ./platform_linux/build.sh --noninteractive
      ;;
    osx)
      brew install ant p7zip
      curl https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2 -o gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
      tar xfj gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2 -C /Applications/
      rm gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
      curl https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/amazon-corretto-8.232.09.1-macosx-x64.pkg > amazon-corretto-8.232.09.1-macosx-x64.pkg
      installer -pkg amazon-corretto-8.232.09.1-macosx-x64.pkg -target /
      rm amazon-corretto-8.232.09.1-macosx-x64.pkg
      ./platform_osx/build.sh
      ;;
    esac;
    javac -version;

script:
  - ant
  - ant check_fw
  - ant -Dbuild.bundle=true bundle

before_deploy:
  - pwd
  - ls ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}/build
  - ls ${TRAVIS_BUILD_DIR}/build/bundles
    
deploy:
  provider: releases
  api_key:
    secure: LlmFhw4NWvaRzlefhBs6L0JXdasgh8t8mjAXxR/bYgEf50zBHdO3bAvEOg2IrFF4th/cWIO8130UkboZ7pgpyrct8jrGE7knWeFgbgdW2JYobpgSx5fthX036xhx6OiShnYgOnxDds68jJK9duLA2MDrQov5itzPdrEgZuSqgYYusiV4x1lJ2iEdOErO8N6Om25M2QAVVsbu6wb5RjHbf/Uf+X1B2Mb+9J33vFnCr5P0/IBQxQkhlSA7V7RiqRyOtC2QrPsmoeAc7QjxeAClGYzWMjQ/2WNfEX8/9ZdYlf48qYnoFqbuQDkjgOxKencj9gFWJdgJw8KxL+ygU51kuvTdZaixY82Y/C34kDd4WyxO1kKS7jyvm/MWEnap/wYly+woiplrjjTMM+a6OwG0YMjpbxZn6GjUB0YP91libmLSNggwQMYxLpkSoEyAsjVM8pEH4Y+6MgmU6UQqpnUat9PnNG/BGXoTWRWefu771nWSPMW1bzds0vEF54I0daISd8gUwNAuBYSPW38woTLBzPd+M15uJ9ThVD6EfwJsifZ5RDNGSr6JFn37sKQ7Imcu7d3QKVXV9URpOZs/enJmfiGgVaKXCWA0Cw1rSP90XK8ERJqguQJ5uGfuAMcWuXzgvXAVPzDopY1ZzYHFqd3B+ro2WmsqzT8OLGKdlrfsFX0=
  file: 
    - build/bundles/*
    - build/runtime/*/axo_runtime*
  file_glob: true  
  skip_cleanup: true
  on:
    repo: axoloti/axoloti
    tags: true
    all_branches: true
git:
    depth: 1000
